function TF=TF_SwingBar(frame,t,q,p,u,s)
    TF=eye(4,4);
%SWITCHCASE_

		switch frame
		    case 1
		        TF=TF_1(t,q,p,u,s);
		    case 2
		        TF=TF_2(t,q,p,u,s);
		    case 3
		        TF=TF_3(t,q,p,u,s);
		    case 4
		        TF=TF_4(t,q,p,u,s);
		    case 5
		        TF=TF_5(t,q,p,u,s);
		    case 6
		        TF=TF_6(t,q,p,u,s);
		    case 7
		        TF=TF_7(t,q,p,u,s);
		    case 8
		        TF=TF_8(t,q,p,u,s);
		end

        

	function out1 = TF_1(t,in2,DISCRETE,in4,in5)
	%TF_1
	%    OUT1 = TF_1(T,IN2,DISCRETE,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:39:21
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_2(t,in2,DISCRETE,in4,in5)
	%TF_2
	%    OUT1 = TF_2(T,IN2,DISCRETE,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:39:21
	q1__dt_0 = in2(1,:);
	t2 = cos(q1__dt_0);
	t3 = sin(q1__dt_0);
	out1 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2,t3,0.0,1.0],[4,4]);
	end

	function out1 = TF_3(t,in2,DISCRETE,in4,in5)
	%TF_3
	%    OUT1 = TF_3(T,IN2,DISCRETE,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:39:21
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.0./2.0,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_4(t,in2,DISCRETE,in4,in5)
	%TF_4
	%    OUT1 = TF_4(T,IN2,DISCRETE,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:39:22
	bj_1__dt_0 = in5(1,:);
	bj_2__dt_0 = in5(2,:);
	bj_3__dt_0 = in5(3,:);
	bj_4__dt_0 = in5(4,:);
	t2 = bj_2__dt_0.*bj_3__dt_0.*2.0;
	t3 = bj_4__dt_0.^2;
	t4 = bj_1__dt_0.*bj_3__dt_0.*2.0;
	t5 = bj_2__dt_0.*bj_4__dt_0.*2.0;
	t6 = bj_3__dt_0.*bj_4__dt_0.*2.0;
	t7 = bj_2__dt_0.^2;
	t8 = bj_3__dt_0.^2;
	out1 = reshape([t3.*-2.0-t8.*2.0+1.0,t2+bj_1__dt_0.*bj_4__dt_0.*2.0,-t4+t5,0.0,t2-bj_1__dt_0.*bj_4__dt_0.*2.0,t3.*-2.0-t7.*2.0+1.0,t6+bj_1__dt_0.*bj_2__dt_0.*2.0,0.0,t4+t5,t6-bj_1__dt_0.*bj_2__dt_0.*2.0,t7.*-2.0-t8.*2.0+1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_5(t,in2,DISCRETE,in4,in5)
	%TF_5
	%    OUT1 = TF_5(T,IN2,DISCRETE,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:39:22
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.0,1.0],[4,4]);
	end

	function out1 = TF_6(t,in2,DISCRETE,in4,in5)
	%TF_6
	%    OUT1 = TF_6(T,IN2,DISCRETE,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:39:22
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0./2.0,1.0],[4,4]);
	end

	function out1 = TF_7(t,in2,DISCRETE,in4,in5)
	%TF_7
	%    OUT1 = TF_7(T,IN2,DISCRETE,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:39:22
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0./2.0,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_8(t,in2,DISCRETE,in4,in5)
	%TF_8
	%    OUT1 = TF_8(T,IN2,DISCRETE,IN4,IN5)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:39:22
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.0./4.0,0.0,0.0,1.0],[4,4]);
	end

end

