function TF=TF_PassiveWalker(frame,t,q,p,u,s)
    TF=eye(4,4);
%SWITCHCASE_

		switch frame
		    case 1
		        TF=TF_1(t,q,p,u,s);
		    case 2
		        TF=TF_2(t,q,p,u,s);
		    case 3
		        TF=TF_3(t,q,p,u,s);
		    case 4
		        TF=TF_4(t,q,p,u,s);
		    case 5
		        TF=TF_5(t,q,p,u,s);
		    case 6
		        TF=TF_6(t,q,p,u,s);
		    case 7
		        TF=TF_7(t,q,p,u,s);
		    case 8
		        TF=TF_8(t,q,p,u,s);
		    case 9
		        TF=TF_9(t,q,p,u,s);
		    case 10
		        TF=TF_10(t,q,p,u,s);
		    case 11
		        TF=TF_11(t,q,p,u,s);
		    case 12
		        TF=TF_12(t,q,p,u,s);
		end

        

	function out1 = TF_1(t,in2,in3,in4,NHSIGNAL)
	%TF_1
	%    OUT1 = TF_1(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:34
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_2(t,in2,in3,in4,NHSIGNAL)
	%TF_2
	%    OUT1 = TF_2(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:34
	a = in4(1,:);
	t2 = sin(a);
	t3 = cos(a);
	out1 = reshape([t3,t2,0.0,0.0,-t2,t3,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_3(t,in2,in3,in4,NHSIGNAL)
	%TF_3
	%    OUT1 = TF_3(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:34
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_4(t,in2,in3,in4,NHSIGNAL)
	%TF_4
	%    OUT1 = TF_4(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:34
	qx__dt_0 = in2(1,:);
	qy__dt_0 = in2(2,:);
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,qx__dt_0,qy__dt_0,0.0,1.0],[4,4]);
	end

	function out1 = TF_5(t,in2,in3,in4,NHSIGNAL)
	%TF_5
	%    OUT1 = TF_5(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:35
	qi1__dt_0 = in2(3,:);
	t2 = sin(qi1__dt_0);
	t3 = cos(qi1__dt_0);
	out1 = reshape([-t2,t3,0.0,0.0,-t3,-t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(1.0./2.0),t3.*(-1.0./2.0),0.0,1.0],[4,4]);
	end

	function out1 = TF_6(t,in2,in3,in4,NHSIGNAL)
	%TF_6
	%    OUT1 = TF_6(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:35
	qo1__dt_0 = in2(5,:);
	t2 = sin(qo1__dt_0);
	t3 = cos(qo1__dt_0);
	out1 = reshape([-t2,t3,0.0,0.0,-t3,-t2,0.0,0.0,0.0,0.0,1.0,0.0,t2.*(1.0./2.0),t3.*(-1.0./2.0),0.0,1.0],[4,4]);
	end

	function out1 = TF_7(t,in2,in3,in4,NHSIGNAL)
	%TF_7
	%    OUT1 = TF_7(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:35
	qi1__dt_0 = in2(3,:);
	qi2__dt_0 = in2(4,:);
	t2 = qi1__dt_0-qi2__dt_0;
	t3 = cos(t2);
	t4 = sin(t2);
	out1 = reshape([t3,-t4,0.0,0.0,t4,t3,0.0,0.0,0.0,0.0,1.0,0.0,t3.*(-1.0./2.0),t4.*(1.0./2.0),0.0,1.0],[4,4]);
	end

	function out1 = TF_8(t,in2,in3,in4,NHSIGNAL)
	%TF_8
	%    OUT1 = TF_8(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:35
	qo1__dt_0 = in2(5,:);
	qo2__dt_0 = in2(6,:);
	t2 = qo1__dt_0-qo2__dt_0;
	t3 = cos(t2);
	t4 = sin(t2);
	out1 = reshape([t3,-t4,0.0,0.0,t4,t3,0.0,0.0,0.0,0.0,1.0,0.0,t3.*(-1.0./2.0),t4.*(1.0./2.0),0.0,1.0],[4,4]);
	end

	function out1 = TF_9(t,in2,in3,in4,NHSIGNAL)
	%TF_9
	%    OUT1 = TF_9(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:35
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0./1.0e1,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_10(t,in2,in3,in4,NHSIGNAL)
	%TF_10
	%    OUT1 = TF_10(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:35
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0./1.0e1,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_11(t,in2,in3,in4,NHSIGNAL)
	%TF_11
	%    OUT1 = TF_11(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:36
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.1e1./5.0e1,0.0,0.0,1.0],[4,4]);
	end

	function out1 = TF_12(t,in2,in3,in4,NHSIGNAL)
	%TF_12
	%    OUT1 = TF_12(T,IN2,IN3,IN4,NHSIGNAL)
	%    This function was generated by the Symbolic Math Toolbox version 7.2.
	%    06-Apr-2018 17:33:36
	out1 = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.1e1./5.0e1,0.0,0.0,1.0],[4,4]);
	end

end

